# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

# Use a Docker container
pool:
  vmImage: 'ubuntu-latest'
  demands:
    - docker

container: 
  image: node:18  # Use Node.js 18.x Docker image

steps:
- checkout: self
  displayName: 'Checkout code from GitHub'

- script: |
    node -v
    npm -v
    npx -v
  displayName: 'Check Node.js, npm, and npx versions'

- script: |
    npm install playwright
    npx playwright --version
  displayName: 'Install and Check Playwright'
