# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: self
  displayName: 'Checkout code from GitHub'

# Step 2: Install Node.js (Use version 18.x, required for Playwright)
- task: UseNode@1
  inputs:
    versionSpec: '18.x'  # Ensure Node.js 18.x is installed
  displayName: 'Install Node.js 18.x'

# Step 3: Install npm dependencies including Playwright
- script: |
    npm install playwright
  displayName: 'Install Playwright and npm dependencies'

# Step 4: Check Node.js and Playwright versions (Debugging)
- script: |
    node -v
    npm -v
    npx playwright --version
  displayName: 'Check Node.js and Playwright versions'

# Step 5: Run Playwright tests (Headed mode)
- script: |
    /bin/bash -c "npx playwright test --headed"
  displayName: 'Run Playwright tests'