# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Step 1: Install Node.js (Required for Playwright)
- task: UseNode@1
  inputs:
    versionSpec: '16.x'   # Adjust the Node.js version if needed
  displayName: 'Install Node.js'

# Step 2: Install dependencies
- script: |
    npm install
  displayName: 'Install npm dependencies'  

# Step 3: Install Playwright dependencies
- script: |
    npx playwright install-deps
  displayName: 'Install Playwright dependencies'

# Step 4: Run Playwright tests
- script: |
    npx playwright test
  displayName: 'npx playwright test --headed'