# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: self
  displayName: 'Checkout code from GitHub'

- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'
- script: npm ci
  displayName: 'npm ci'
# Step 4: Install xvfb
- script: |
    sudo apt-get update
    sudo apt-get install -y xvfb
  displayName: 'Install xvfb'  
- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'
- script: |
    xvfb-run -a npx playwright test --headed
  displayName: 'Run Playwright Tests with xvfb'
  env:
    CI: 'true'