# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Step 1: Checkout the code from GitHub
- checkout: self
  displayName: 'Checkout code from GitHub'

# Step 2: Install Node.js (Use version 18.x, required for Playwright)
- task: UseNode@1
  inputs:
    versionSpec: '18.x'  # Ensure Node.js 18.x is installed
    checkLatest: true    # Always ensure the latest available version is used
  displayName: 'Install Node.js 18.x'

# Step 3: Verify Node.js and npm Versions
- script: |
    echo "Node.js and npm versions"
    node -v
    npm -v
  displayName: 'Check Node.js and npm versions'

# Step 4: Clear npm cache
- script: |
    npm cache clean --force
  displayName: 'Clear npm cache'

# Step 5: Install npm dependencies including Playwright
- script: |
    npm install
  displayName: 'Install npm dependencies'

# Step 6: Verify Playwright Installation
- script: |
    npx playwright --version
  displayName: 'Check Playwright installation'

# Step 7: Run Playwright Tests
- script: |
    npx playwright test --headed
  displayName: 'Run Playwright tests'