# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Step 1: Checkout the code from GitHub
- checkout: self
  displayName: 'Checkout code from GitHub'

# Step 2: Install Node.js (Use version 18.x, required for Playwright)
- task: UseNode@1
  inputs:
    versionSpec: '18.x'  # Ensure Node.js 18.x is installed
    checkLatest: true    # Always ensure the latest available version is used
  displayName: 'Install Node.js 18.x'

# Step 3: Clear npm cache and verify Node.js version
- script: |
    npm cache clean --force
    node -v
    npm -v
  displayName: 'Clear npm cache and check Node.js version'

# Step 4: Install npm dependencies including Playwright
- script: |
    npm install
  displayName: 'Install Playwright and npm dependencies'

# Step 5: Run Basic Commands to Check Environment
- script: |
    echo "Basic test command"
    ls -l
  displayName: 'Run Basic Commands'

# Step 6: Verify Playwright Installation
- script: |
    npm install playwright
    npx playwright --version
  displayName: 'Install and Check Playwright'

# Step 7: Run Playwright Tests with sh (if necessary)
- script: |
    sh -c "npx playwright test --headed"
  displayName: 'Run Playwright Tests with sh'