# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

steps:
# Step 1: Checkout the code from GitHub
- checkout: self
  displayName: 'Checkout code from GitHub'

# Step 2: Install Node.js (Use version 18.x, required for Playwright)
- task: UseNode@1
  inputs:
    versionSpec: '18.x'  # Ensure Node.js 18.x is installed
    checkLatest: true    # Always ensure the latest available version is used
  displayName: 'Install Node.js 18.x'

# Step 3: Log environment details (for debugging)
- script: |
    echo "Logging system information"
    uname -a
    node -v
    npm -v
    npx --version
    printenv
  displayName: 'Log system information and environment variables'

# Step 4: Install npm dependencies including Playwright
- script: |
    echo "Installing npm dependencies"
    npm install
  displayName: 'Install Playwright and npm dependencies'

# Step 5: Verify Playwright installation (for debugging)
- script: |
    echo "Checking Playwright version"
    npx playwright --version
  displayName: 'Check Playwright installation'

# Step 6: Run Playwright tests (without Bash wrapping)
- script: |
    echo "Running Playwright tests"
    npx playwright test --headed || echo "Playwright tests failed"
  displayName: 'Run Playwright tests (with logging)'