# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Step 1: Checkout the code from GitHub
- checkout: self
  displayName: 'Checkout code from GitHub'

# Step 2: Install Node.js (Required for Playwright)
- task: UseNode@1
  inputs:
    versionSpec: '16.x'  # Specify the version of Node.js. Adjust as needed.
  displayName: 'Install Node.js'

# Step 3: Install npm dependencies
- script: |
    npm install
  displayName: 'Install npm dependencies'

# Step 4: Install Playwright dependencies (For Linux environments)
- script: |
    npx playwright install-deps
  displayName: 'Install Playwright dependencies'

# Step 5: Run Playwright tests
- script: |
    npx playwright test --headed
  displayName: 'Run Playwright tests'